name: Publish

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Verify
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
        
    - name: Version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      
    - name: Pack    
      run: |
        dotnet pack Source/Blick.Logging.Core.csproj --configuration Release --no-build --output . /p:Version=${VERSION}
      
    - name: Push
      run: |
        dotnet nuget push Blick.Logging.Core.${VERSION}.nupkg --source https://nuget.pkg.github.com/Webclix/index.json --api-key ${{ secrets.WEBCLIX_PACKAGE_READ_AND_WRITE }} --skip-duplicate
